/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CoordinadorBoleto;
import Controlador.CoordinadorRuta;
import Modelo.BoletoVo;
import Modelo.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pablo
 */
public class VentaBoletos extends javax.swing.JFrame {

    BoletoVo boleto = new BoletoVo();
    private CoordinadorBoleto miCoordinadorBoleto=new CoordinadorBoleto();
    public VentaBoletos() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        mostrarDatos("");
        
    }

    void mostrarDatos(String valor){
        
        Conexion conx=new Conexion();
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Origen ");
        modelo.addColumn("Destino ");
        
        tblRuta1.setModel(modelo);
        String sql="";
        if(valor.equals("")){
            sql="SELECT * FROM ruta";
        }
        else{
            sql="SELECT * FROM ruta WHERE IdRuta='"+valor+"'";
        }
        String []datos=new String[3];
        try {
            Statement st= conx.getConexion().createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(3);
                modelo.addRow(datos);
            }
            tblRuta1.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarRuta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        cbxCliente = new javax.swing.JComboBox<>();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cbxMes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxDia = new javax.swing.JComboBox<>();
        cbxHora = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRuta1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        btnVender = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtNBoletos = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lbldescuento = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("VENDER VOLETOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS PERSONALES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel1.setOpaque(false);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("Cedula:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Cliente:");

        cbxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NORMAL", "SOCIO", "VIP" }));

        lblCodigo.setText("Codigo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(61, 61, 61)
                        .addComponent(txtCodigo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(65, 65, 65)
                        .addComponent(txtCedula))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdad)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 132, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido)
                            .addComponent(txtNombre))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACION VIAJE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel2.setOpaque(false);

        cbxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));

        jLabel6.setText("MES");

        jLabel7.setText("DIA");

        jLabel8.setText("HORA");

        cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbxHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1:00", "2:00", "3:00", "4:00", "5:00", "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", "24:00" }));

        tblRuta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRuta1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRuta1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRuta1);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Seleccione Ruta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(97, 97, 97))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boleto.png"))); // NOI18N
        btnVender.setText("VENDER");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png"))); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel11.setText("# VOLETOS: ");

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("DESCUENTO: ");

        lbldescuento.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("TOTAL:");

        lblTotal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnRegresar)
                .addGap(45, 45, 45)
                .addComponent(btnVender)
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txtNBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(36, 36, 36)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbldescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVender)
                            .addComponent(btnRegresar)
                            .addComponent(jLabel11)
                            .addComponent(txtNBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbldescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblRuta1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRuta1MouseClicked
        // TODO add your handling code here:

         int fila=tblRuta1.getSelectedRow();
        
        if(fila>=0){
            
            boleto.setOrigen(tblRuta1.getValueAt(fila, 1).toString());            
            boleto.setDestino(tblRuta1.getValueAt(fila,2).toString());
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No selecciono fila");
        }
    }//GEN-LAST:event_tblRuta1MouseClicked

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        // TODO add your handling code here:
        int valorBoleto= 12;
        
        // verifico que tipo de cliente son
        if (cbxCliente.getSelectedItem()== "NORMAL")
        {
            //verifico la edad para saber que descuento se le aplica
            if(Integer.parseInt(txtEdad.getText())>= 70)
            {
                int costoBoleto= 13*Integer.parseInt(txtNBoletos.getText());
                double descuento= costoBoleto*0.10;
                lbldescuento.setText(String.valueOf(descuento));
                double costo= costoBoleto-descuento;
                lblTotal.setText(String.valueOf(costo));
                boleto.setIdboleto(txtCodigo.getText());
                boleto.setNombre(txtNombre.getText());
                boleto.setApellido(txtApellido.getText());
                boleto.setCedula(txtCedula.getText());
                boleto.setEdad(txtEdad.getText());
                boleto.setTipoCliente(cbxCliente.getSelectedItem().toString());
                String fecha= cbxDia.getSelectedItem().toString()+'-'+cbxMes.getSelectedItem().toString()+'-'+cbxHora.getSelectedItem().toString();
                boleto.setFecha(fecha);
                boleto.setNumBoletos(Integer.parseInt(txtNBoletos.getText()));
                boleto.setDescuento(Double.parseDouble(lbldescuento.getText()));
                boleto.setTotal(Double.parseDouble(lblTotal.getText()));
                miCoordinadorBoleto.venderBoleto(boleto);
            }

            if(Integer.parseInt(txtEdad.getText())<= 5)
            {
                int costoBoleto= 13*Integer.parseInt(txtNBoletos.getText());
                double descuento= costoBoleto*0.05;
                lbldescuento.setText(String.valueOf(descuento));
                double costo= costoBoleto-descuento;
                lblTotal.setText(String.valueOf(costo));
                boleto.setIdboleto(txtCodigo.getText());
                boleto.setNombre(txtNombre.getText());
                boleto.setApellido(txtApellido.getText());
                boleto.setCedula(txtCedula.getText());
                boleto.setEdad(txtEdad.getText());
                boleto.setTipoCliente(cbxCliente.getSelectedItem().toString());
                String fecha= cbxDia.getSelectedItem().toString()+'-'+cbxMes.getSelectedItem().toString()+'-'+cbxHora.getSelectedItem().toString();
                boleto.setFecha(fecha);
                boleto.setNumBoletos(Integer.parseInt(txtNBoletos.getText()));
                boleto.setDescuento(Double.parseDouble(lbldescuento.getText()));
                boleto.setTotal(Double.parseDouble(lblTotal.getText()));
                miCoordinadorBoleto.venderBoleto(boleto);
                
            } 
            if(Integer.parseInt(txtEdad.getText())<70 && Integer.parseInt(txtEdad.getText())>5)
            {
                int costoBoleto= 13*Integer.parseInt(txtNBoletos.getText());
                double descuento= 0;
                lbldescuento.setText(String.valueOf(descuento));
                double costo= costoBoleto-descuento;
                lblTotal.setText(String.valueOf(costo));
                boleto.setIdboleto(txtCodigo.getText());
                boleto.setNombre(txtNombre.getText());
                boleto.setApellido(txtApellido.getText());
                boleto.setCedula(txtCedula.getText());
                boleto.setEdad(txtEdad.getText());
                boleto.setTipoCliente(cbxCliente.getSelectedItem().toString());
                String fecha= cbxDia.getSelectedItem().toString()+'-'+cbxMes.getSelectedItem().toString()+'-'+cbxHora.getSelectedItem().toString();
                boleto.setFecha(fecha);
                boleto.setNumBoletos(Integer.parseInt(txtNBoletos.getText()));
                boleto.setDescuento(Double.parseDouble(lbldescuento.getText()));
                boleto.setTotal(Double.parseDouble(lblTotal.getText()));
                miCoordinadorBoleto.venderBoleto(boleto);
                
            }
          }
        //verificamos que tipo de cliente es
        if (cbxCliente.getSelectedItem()== "SOCIO")
        {
            //verifico la edad para saber que descuento se le aplica
            if(Integer.parseInt(txtEdad.getText())>= 70)
            {
                int costoBoleto= 13*Integer.parseInt(txtNBoletos.getText());
                double descuento= costoBoleto*0.12;
                lbldescuento.setText(String.valueOf(descuento));
                double costo= costoBoleto-descuento;
                lblTotal.setText(String.valueOf(costo));
                lblTotal.setText(String.valueOf(costo));
                boleto.setIdboleto(txtCodigo.getText());
                boleto.setNombre(txtNombre.getText());
                boleto.setApellido(txtApellido.getText());
                boleto.setCedula(txtCedula.getText());
                boleto.setEdad(txtEdad.getText());
                boleto.setTipoCliente(cbxCliente.getSelectedItem().toString());
                String fecha= cbxDia.getSelectedItem().toString()+'-'+cbxMes.getSelectedItem().toString()+'-'+cbxHora.getSelectedItem().toString();
                boleto.setFecha(fecha);
                boleto.setNumBoletos(Integer.parseInt(txtNBoletos.getText()));
                boleto.setDescuento(Double.parseDouble(lbldescuento.getText()));
                boleto.setTotal(Double.parseDouble(lblTotal.getText()));
                miCoordinadorBoleto.venderBoleto(boleto);
                
            }
            if(Integer.parseInt(txtEdad.getText())<= 5)
            {
                int costoBoleto= 13*Integer.parseInt(txtNBoletos.getText());
                double descuento= costoBoleto*0.07;
                lbldescuento.setText(String.valueOf(descuento));
                double costo= costoBoleto-descuento;
                lblTotal.setText(String.valueOf(costo));
                boleto.setIdboleto(txtCodigo.getText());
                boleto.setNombre(txtNombre.getText());
                boleto.setApellido(txtApellido.getText());
                boleto.setCedula(txtCedula.getText());
                boleto.setEdad(txtEdad.getText());
                boleto.setTipoCliente(cbxCliente.getSelectedItem().toString());
                String fecha= cbxDia.getSelectedItem().toString()+'-'+cbxMes.getSelectedItem().toString()+'-'+cbxHora.getSelectedItem().toString();
                boleto.setFecha(fecha);
                boleto.setNumBoletos(Integer.parseInt(txtNBoletos.getText()));
                boleto.setDescuento(Double.parseDouble(lbldescuento.getText()));
                boleto.setTotal(Double.parseDouble(lblTotal.getText()));
                miCoordinadorBoleto.venderBoleto(boleto);
                
            }
            if(Integer.parseInt(txtEdad.getText())<70 && Integer.parseInt(txtEdad.getText())>5)
            {
                int costoBoleto= 13*Integer.parseInt(txtNBoletos.getText());
                double descuento= costoBoleto*0.02;
                lbldescuento.setText(String.valueOf(descuento));
                double costo= costoBoleto-descuento;
                lblTotal.setText(String.valueOf(costo));
                boleto.setIdboleto(txtCodigo.getText());
                boleto.setNombre(txtNombre.getText());
                boleto.setApellido(txtApellido.getText());
                boleto.setCedula(txtCedula.getText());
                boleto.setEdad(txtEdad.getText());
                boleto.setTipoCliente(cbxCliente.getSelectedItem().toString());
                String fecha= cbxDia.getSelectedItem().toString()+'-'+cbxMes.getSelectedItem().toString()+'-'+cbxHora.getSelectedItem().toString();
                boleto.setFecha(fecha);
                boleto.setNumBoletos(Integer.parseInt(txtNBoletos.getText()));
                boleto.setDescuento(Double.parseDouble(lbldescuento.getText()));
                boleto.setTotal(Double.parseDouble(lblTotal.getText()));
                miCoordinadorBoleto.venderBoleto(boleto);
            }
        }
        if (cbxCliente.getSelectedItem()== "VIP")
        {
            //verifico la edad para saber que descuento se le aplica
            if(Integer.parseInt(txtEdad.getText())>= 70)
            {
                int costoBoleto= 13*Integer.parseInt(txtNBoletos.getText());
                double descuento= costoBoleto*0.14;
                lbldescuento.setText(String.valueOf(descuento));
                double costo= costoBoleto-descuento;
                lblTotal.setText(String.valueOf(costo));
                boleto.setIdboleto(txtCodigo.getText());
                boleto.setNombre(txtNombre.getText());
                boleto.setApellido(txtApellido.getText());
                boleto.setCedula(txtCedula.getText());
                boleto.setEdad(txtEdad.getText());
                boleto.setTipoCliente(cbxCliente.getSelectedItem().toString());
                String fecha= cbxDia.getSelectedItem().toString()+'-'+cbxMes.getSelectedItem().toString()+'-'+cbxHora.getSelectedItem().toString();
                boleto.setFecha(fecha);
                boleto.setNumBoletos(Integer.parseInt(txtNBoletos.getText()));
                boleto.setDescuento(Double.parseDouble(lbldescuento.getText()));
                boleto.setTotal(Double.parseDouble(lblTotal.getText()));
                miCoordinadorBoleto.venderBoleto(boleto);
                
            }
            if(Integer.parseInt(txtEdad.getText())<= 5)
            {
                int costoBoleto= 13*Integer.parseInt(txtNBoletos.getText());
                double descuento= costoBoleto*0.09;
                lbldescuento.setText(String.valueOf(descuento));
                double costo= costoBoleto-descuento;
                lblTotal.setText(String.valueOf(costo));
                boleto.setIdboleto(txtCodigo.getText());
                boleto.setNombre(txtNombre.getText());
                boleto.setApellido(txtApellido.getText());
                boleto.setCedula(txtCedula.getText());
                boleto.setEdad(txtEdad.getText());
                boleto.setTipoCliente(cbxCliente.getSelectedItem().toString());
                String fecha= cbxDia.getSelectedItem().toString()+'-'+cbxMes.getSelectedItem().toString()+'-'+cbxHora.getSelectedItem().toString();
                boleto.setFecha(fecha);
                boleto.setNumBoletos(Integer.parseInt(txtNBoletos.getText()));
                boleto.setDescuento(Double.parseDouble(lbldescuento.getText()));
                boleto.setTotal(Double.parseDouble(lblTotal.getText()));
                miCoordinadorBoleto.venderBoleto(boleto);
            }
            if(Integer.parseInt(txtEdad.getText())<70 && Integer.parseInt(txtEdad.getText())>5)
            {
                int costoBoleto= 13*Integer.parseInt(txtNBoletos.getText());
                double descuento= costoBoleto*0.04;
                lbldescuento.setText(String.valueOf(descuento));
                double costo= costoBoleto-descuento;
                lblTotal.setText(String.valueOf(costo));
                boleto.setIdboleto(txtCodigo.getText());
                boleto.setNombre(txtNombre.getText());
                boleto.setApellido(txtApellido.getText());
                boleto.setCedula(txtCedula.getText());
                boleto.setEdad(txtEdad.getText());
                boleto.setTipoCliente(cbxCliente.getSelectedItem().toString());
                String fecha= cbxDia.getSelectedItem().toString()+'-'+cbxMes.getSelectedItem().toString()+'-'+cbxHora.getSelectedItem().toString();
                boleto.setFecha(fecha);
                boleto.setNumBoletos(Integer.parseInt(txtNBoletos.getText()));
                boleto.setDescuento(Double.parseDouble(lbldescuento.getText()));
                boleto.setTotal(Double.parseDouble(lblTotal.getText()));
                miCoordinadorBoleto.venderBoleto(boleto);
            }
        }
        txtCodigo.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCedula.setText("");
        txtEdad.setText("");
        txtNBoletos.setText("");
        lbldescuento.setText("");
        lblTotal.setText("");
        
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Modulo modulo = new Modulo();
        modulo.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaBoletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaBoletos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVender;
    private javax.swing.JComboBox<String> cbxCliente;
    private javax.swing.JComboBox<String> cbxDia;
    private javax.swing.JComboBox<String> cbxHora;
    private javax.swing.JComboBox<String> cbxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lbldescuento;
    private javax.swing.JTable tblRuta1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNBoletos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
